#!/usr/bin/env python3
"""Optimize case-study images and regenerate the size manifest.

Drop new PNG/JPG screenshots into public/case-studies/<id>/images/, then run:

    python3 scripts/optimize-case-study-images.py

It converts them to webp at a sane render width, deletes the originals,
rewrites any markdown references, and regenerates
src/content/case-study-images.ts.

Run it after adding or replacing any case-study image — the manifest feeds the
width/height attributes that let CaseStudyBody lazy-load without shifting the
headings that sidebar anchors jump to. Stale manifest means a missing entry,
which silently falls back to eager loading with no reserved box.

Requires Pillow.
"""

import pathlib
import re

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
IMG_ROOT = ROOT / "public/case-studies"
MD_DIR = ROOT / "src/content/case-studies"
MANIFEST = ROOT / "src/content/case-study-images.ts"

# The case-study content column is max-w-3xl (768px), so 1600 is a
# comfortable 2x for retina without shipping needless pixels.
MAX_WIDTH = 1600
QUALITY = 85
PAPER = (245, 241, 232)


def to_webp(src: pathlib.Path) -> pathlib.Path:
    im = Image.open(src)
    # Flatten any alpha onto the paper background — these are opaque
    # screenshots, and an alpha channel costs bytes for nothing.
    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        flat = Image.new("RGB", im.size, PAPER)
        flat.paste(im, mask=im.split()[-1])
        im = flat
    else:
        im = im.convert("RGB")

    if im.width > MAX_WIDTH:
        im = im.resize(
            (MAX_WIDTH, round(MAX_WIDTH * im.height / im.width)), Image.LANCZOS
        )

    dst = src.with_suffix(".webp")
    im.save(dst, "WEBP", quality=QUALITY, method=6)
    if dst != src:
        src.unlink()
    return dst


def main() -> None:
    before = after = 0
    converted = 0
    for src in sorted(IMG_ROOT.rglob("*")):
        if src.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
            continue
        before += src.stat().st_size
        after += to_webp(src).stat().st_size
        converted += 1

    for md in sorted(MD_DIR.glob("*.md")):
        text = md.read_text()
        rewritten = re.sub(
            r"\(images/([^)]+?)\.(?:png|jpg|jpeg)\)", r"(images/\1.webp)", text
        )
        if rewritten != text:
            md.write_text(rewritten)
            print(f"rewrote image refs in {md.name}")

    rows = []
    for p in sorted(IMG_ROOT.rglob("*.webp")):
        im = Image.open(p)
        rows.append(f'  "{p.relative_to(IMG_ROOT)}": [{im.width}, {im.height}],')

    MANIFEST.write_text(
        "// Generated by scripts/optimize-case-study-images.py — do not edit by hand.\n"
        "// Intrinsic dimensions let CaseStudyBody reserve each image's box before\n"
        "// it loads, which is what keeps lazy-loading from shifting the headings\n"
        "// that sidebar anchors jump to.\n"
        "export const caseStudyImageSizes: Record<string, [number, number]> = {\n"
        + "\n".join(rows)
        + "\n};\n"
    )

    if converted:
        print(f"converted {converted} images: "
              f"{before / 1048576:.1f} MB -> {after / 1048576:.1f} MB")
    print(f"manifest: {len(rows)} entries")


if __name__ == "__main__":
    main()
